/**
 * LoginSession represents the structure of a user's login session, including details about the device used for login, location information, and session management fields.
 */

import { type TimeStamp } from "./common";

export type DeviceType = "mobile" | "desktop" | "tablet" | "unknown";

/**
 * LoginSession represents the structure of a user's login session, including details about the device used for login, location information, and session management fields.
 *
 * userId is _id generated by the database
 * sessionId is a unique identifier for the session, typically a UUID or similar string.
 * ipAddress is the IP address from which the user logged in.
 * refreshToken is the refresh token associated with the session, used for validating refresh token requests.
 * device contains information about the device used for login, including type, operating system, browser, and an optional device name.
 * location is an optional field that can include geographic information about the login location, such as country, region, city, latitude, and longitude.
 * isActive indicates whether the session is currently active.
 * lastActivityAt is a timestamp of the last activity in the session, which can be used for session timeout and management purposes.
 *
 */

export interface LoginSession extends TimeStamp {
  userId: string;
  sessionId: string;
  ipAddress: string;
  refreshTokenHash: string;
  refreshExpiresAt: Date;
  device?: {
    type: DeviceType;
    os: string;
    browser: string;
    deviceName?: string;
  };

  location?: {
    country?: string;
    region?: string;
    city?: string;
    latitude?: number;
    longitude?: number;
  };

  isActive: boolean;
  lastActivityAt: Date;
}
