import { type TimeStamp } from "./common";

/**
 * Verifier represents the structure of a token used for verification purposes, such as password reset or email verification.
 * It includes fields for the user ID, token value, and expiration date, along with timestamp fields for tracking when the token was created and last updated.
 *
 * userId is _id generated by the database
 * tokenHash is the hashed value of the token sent to the user, used for secure verification without exposing the actual token value in the database.
 * expiresAt indicates the date and time when the token will expire, ensuring that tokens are only valid for a limited period, enhancing security by preventing the use of old or compromised tokens.
 */
export interface Verifier {
  userId: string;
  tokenHash: string;
  expiresAt: Date;
}

/**
 * PasswordResetToken and EmailVerificationToken are specific types of Verifier used for password reset and email verification processes, respectively.
 * They inherit the structure of Verifier, allowing for consistent handling of token-related operations across the application.
 */
export type PasswordResetToken = Verifier & TimeStamp;

/**
 * EmailVerificationToken is a specific type of Verifier used for email verification processes.
 * It inherits the structure of Verifier, allowing for consistent handling of token-related operations across the application.
 */
export type EmailVerificationToken = Verifier & TimeStamp;
