import { type TimeStamp } from "./common";

/**
 *
 * PublicUser represents the structure of a user's public information, including non-sensitive details such as email, name, and display picture URL.
 * It extends the TimeStamp interface, which includes fields for tracking when the user was created and last updated.
 * This structure is essential for displaying user information in the application without exposing sensitive data such as password hashes or email verification status.
 * The PublicUser interface includes fields for the user's email, name, and an optional display picture URL, along with timestamp fields for tracking when the user was created and last updated.
 * This structure is used for scenarios where only non-sensitive user information is required, such as displaying user profiles or lists of users, while keeping sensitive information secure and private.
 *
 * email: The email address of the user, which is a unique identifier for the user and can be used for communication and authentication purposes.
 * name: The name of the user, which can be used for display purposes in the application.
 * displayPictureUrl: An optional URL pointing to the user's display picture, which can be used for visual representation of the user in the application.
 *
 */

export interface PublicUser {
  email: string;
  name: string;
  displayPictureUrl?: string;
}
/**
 * Usersnap represents the structure of a user in the system, including sensitive information such as password hash and email verification status.
 * It extends the PublicUser interface, which contains non-sensitive information about the user, allowing for a clear separation between public and private user data.
 * The Usersnap interface includes fields for the user's email, name, display picture URL, password hash, and email verification status, along with timestamp fields for tracking when the user was created and last updated.
 * This structure is essential for managing user accounts, authentication, and authorization processes within the application.
 *
 * userId is _id generated by the database
 * passwordHash is the hashed version of the user's password, used for authentication purposes.
 *
 *
 */
export interface UserSnap extends PublicUser, TimeStamp {
  userId: string;
  passwordHash: string;
}
